spring.application.name=ChemLearn
jwt.secret=nqdN4rqus2KHVxCK05kGEy73QMSESI0pMvc+TDQuj9o=

spring.datasource.url=jdbc:postgresql://localhost:5432/chem_learn
spring.datasource.username=postgres
spring.datasource.password=1231
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

#logging.level.org.hibernate.engine.internal=DEBUG
#spring.web.error.include-message=always
