-- 1. NHÓM BẢNG USER & ROLE (Giữ nguyên cấu trúc của em)
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       full_name VARCHAR(100) NOT NULL,
                       role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT', 'TEACHER', 'PARENT', 'ADMIN')),
                       avatar_url TEXT,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parents (
                         user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                         phone_number VARCHAR(20),
                         job_title VARCHAR(100)
);

CREATE TABLE students (
                          user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                          grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 6 AND 12),
                          total_points INTEGER DEFAULT 0,
                          current_streak INTEGER DEFAULT 0,
                          parent_id BIGINT REFERENCES parents(user_id) ON DELETE SET NULL, -- Trỏ thẳng vào bảng parents
                          school_name VARCHAR(255)
);

CREATE TABLE teachers (
                          user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                          bio TEXT,
                          specialization VARCHAR(100),
                          degree VARCHAR(100),
                          workplace VARCHAR(255)
);

-- 2. Bảng Classes
CREATE TABLE classes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL,
                         grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 6 AND 12), -- Đã đồng bộ 6-12
    -- QUAN TRỌNG: Chỉ Teacher mới được tạo lớp
                         teacher_id BIGINT REFERENCES teachers(user_id) ON DELETE SET NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Bảng Class Enrollments
CREATE TABLE class_enrollments (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    -- QUAN TRỌNG: Chỉ Student mới được tham gia lớp
                                   student_id BIGINT NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
                                   joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   UNIQUE(class_id, student_id)
);

-- 4. Bảng Chapters (Giữ nguyên)
CREATE TABLE chapters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(200) NOT NULL,
                          description TEXT,
                          grade_level INTEGER NOT NULL,
                          order_index INTEGER DEFAULT 0,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Bảng Lessons (Giữ nguyên)
CREATE TABLE lessons (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
                         title VARCHAR(200) NOT NULL,
                         content_type VARCHAR(50) NOT NULL,
                         video_url TEXT,
                         text_content TEXT,
                         lab_config JSONB,
                         duration_minutes INTEGER DEFAULT 0,
                         order_index INTEGER DEFAULT 0,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Bảng Questions (Giữ nguyên)
CREATE TABLE questions (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
                           content TEXT NOT NULL,
                           question_type VARCHAR(50) DEFAULT 'SINGLE_CHOICE',
                           explanation TEXT,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Bảng Answers (Giữ nguyên)
CREATE TABLE answers (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
                         content TEXT NOT NULL,
                         is_correct BOOLEAN DEFAULT FALSE
);

-- 8. Bảng Lesson Progress
CREATE TABLE lesson_progress (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- QUAN TRỌNG: Chỉ Student mới có tiến độ học tập
                                 student_id BIGINT NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
                                 lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
                                 is_completed BOOLEAN DEFAULT FALSE,
                                 is_locked BOOLEAN DEFAULT TRUE,
                                 last_accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 UNIQUE(student_id, lesson_id)
);

-- 9. Bảng Quiz Attempts
CREATE TABLE quiz_attempts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- QUAN TRỌNG: Chỉ Student mới được làm bài thi
                               student_id BIGINT NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
                               lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
                               score DECIMAL(5, 2) NOT NULL,
                               passed BOOLEAN DEFAULT FALSE,
                               attempt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Bảng Badges (Giữ nguyên)
CREATE TABLE badges (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        description TEXT,
                        icon_url TEXT,
                        criteria_json JSONB
);

-- 11. Bảng User Badges
CREATE TABLE user_badges (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             student_id BIGINT NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
                             badge_id BIGINT NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
                             earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);